# Checkpoint 1: Load and select AI job data

This notebook only uses ideas from the first two Kaggle Pandas lessons. Run each cell in order, then complete the TODO cells yourself.

In [1]:
from pathlib import Path
import pandas as pd

DATA_PATH = Path("../ai_jobs_market_2025_2026.csv")
df = pd.read_csv(DATA_PATH)

## 1. Inspect the dataset

Run the cells and confirm that the dataset has 1,500 rows and 25 columns.

In [2]:
df.head()

,job_id,job_title,job_category,experience_level,years_of_experience,education_required,annual_salary_usd,salary_min_usd,salary_max_usd,city,...,ai_salary_premium_pct,demand_score,demand_growth_yoy_pct,benefits_score_10,posting_year,posting_month,is_senior,is_remote_friendly,is_llm_role,salary_tier
0,AIJOB0001,AI Agent Developer,AI Engineering,Senior (6-9 yrs),7,Master's,239000.0,155000,290000,Boston,...,13.1,96,16.9,6.8,2026,3,1,0,1,Senior ($200-300k)
1,AIJOB0002,Prompt Engineer,AI Engineering,Senior (6-9 yrs),2,Bachelor's,166000.0,90000,200000,London,...,5.4,82,11.6,6.2,2026,1,1,1,1,Upper-Mid ($150-200k)
2,AIJOB0003,LLM Engineer,AI Engineering,Senior (6-9 yrs),4,Associate's,360000.0,160000,300000,Seattle,...,9.1,98,42.7,7.7,2026,1,1,1,1,Elite (>$300k)
3,AIJOB0004,Data Engineer (AI),Data Engineering,Senior (6-9 yrs),3,Bachelor's,161000.0,130000,220000,Singapore,...,12.0,88,6.7,9.5,2026,3,1,1,0,Upper-Mid ($150-200k)
4,AIJOB0005,AI Product Manager,Product,Lead (10+ yrs),5,Bootcamp/Self-taught,283000.0,140000,260000,Los Angeles,...,9.4,85,17.3,8.9,2026,1,1,1,0,Senior ($200-300k)

In [3]:
print("Shape:", df.shape)
print("Columns:")
print(df.columns.tolist())

Shape: (1500, 25)
Columns:
['job_id', 'job_title', 'job_category', 'experience_level', 'years_of_experience', 'education_required', 'annual_salary_usd', 'salary_min_usd', 'salary_max_usd', 'city', 'country', 'remote_work', 'company_size', 'industry', 'required_skills', 'ai_salary_premium_pct', 'demand_score', 'demand_growth_yoy_pct', 'benefits_score_10', 'posting_year', 'posting_month', 'is_senior', 'is_remote_friendly', 'is_llm_role', 'salary_tier']

## 2. Select useful columns

Keep the columns needed for an initial job and salary view.

In [3]:
job_view = df.loc[:, [
    "job_title",
    "job_category",
    "experience_level",
    "annual_salary_usd",
    "country",
    "remote_work",
]]

job_view.head()

,job_title,job_category,experience_level,annual_salary_usd,country,remote_work
0,AI Agent Developer,AI Engineering,Senior (6-9 yrs),239000.0,USA,On-site
1,Prompt Engineer,AI Engineering,Senior (6-9 yrs),166000.0,UK,Hybrid
2,LLM Engineer,AI Engineering,Senior (6-9 yrs),360000.0,USA,Fully Remote
3,Data Engineer (AI),Data Engineering,Senior (6-9 yrs),161000.0,Singapore,Fully Remote
4,AI Product Manager,Product,Lead (10+ yrs),283000.0,USA,Fully Remote

## 3. Your turn: filter rows

Complete the three TODOs. Each result should contain only the requested rows and useful columns.

In [6]:
# TODO 1: Show the first 10 jobs located in the USA.
usa_jobs = df.loc[df["country"]=='USA', ["job_title", "annual_salary_usd", "city"]]
usa_jobs.head(10)

                 job_title  annual_salary_usd           city
0       AI Agent Developer           239000.0         Boston
2             LLM Engineer           360000.0        Seattle
4       AI Product Manager           283000.0    Los Angeles
5       AI Agent Developer           155000.0        Chicago
6     AI Security Engineer           197000.0         Boston
9          Prompt Engineer            90000.0    Los Angeles
20  Multimodal AI Engineer           329000.0        Chicago
22     AI Business Analyst           201000.0    Los Angeles
27             ML Engineer           224000.0  San Francisco
28     AI Business Analyst           216000.0  San Francisco

In [7]:
# TODO 2: Find jobs with annual salaries above 200,000 USD.
high_salary_jobs = df.loc[df['annual_salary_usd']>200000, ["job_title", "experience_level", "annual_salary_usd"]]
high_salary_jobs.head(10)

                 job_title  experience_level  annual_salary_usd
0       AI Agent Developer  Senior (6-9 yrs)           239000.0
2             LLM Engineer  Senior (6-9 yrs)           360000.0
4       AI Product Manager    Lead (10+ yrs)           283000.0
7       Senior ML Engineer     Mid (3-5 yrs)           221000.0
14      AI Agent Developer  Senior (6-9 yrs)           209000.0
18    AI Security Engineer  Senior (6-9 yrs)           228000.0
20  Multimodal AI Engineer  Senior (6-9 yrs)           329000.0
21          MLOps Engineer  Senior (6-9 yrs)           272000.0
22     AI Business Analyst    Lead (10+ yrs)           201000.0
23            RAG Engineer    Lead (10+ yrs)           230000.0

In [11]:
# TODO 3: Find remote LLM roles. Hint: combine two conditions with &.
remote_llm_jobs = df.loc[(df['is_remote_friendly']==1 )& (df['is_llm_role']==1), ["job_title", "country", "remote_work", "annual_salary_usd"]]
remote_llm_jobs.head(10)

                 job_title      country   remote_work  annual_salary_usd
1          Prompt Engineer           UK        Hybrid           166000.0
2             LLM Engineer          USA  Fully Remote           360000.0
11         Prompt Engineer        Japan        Hybrid           118000.0
14      AI Agent Developer          UAE        Hybrid           209000.0
15      AI Agent Developer  Netherlands  Fully Remote           155000.0
23            RAG Engineer       Canada  Fully Remote           230000.0
45            RAG Engineer           UK  Fully Remote           189000.0
55  Generative AI Engineer          USA  Fully Remote           354000.0
72            RAG Engineer          UAE        Hybrid           157000.0
85         Prompt Engineer           UK  Fully Remote           121000.0

## 4. Early observations

Write three observations based only on the tables above. Use concrete evidence such as a job title, salary, country, or number of matching rows.

1. TODO
2. TODO
3. TODO

In [14]:
total_jobs = df.shape[0]

print(f"美国岗位占比：{usa_jobs.shape[0] / total_jobs:.1%}")
print(f"高薪岗位占比：{high_salary_jobs.shape[0] / total_jobs:.1%}")
print(f"远程友好 LLM 岗位占比：{remote_llm_jobs.shape[0] / total_jobs:.1%}")

美国岗位占比：34.3%
高薪岗位占比：40.5%
远程友好 LLM 岗位占比：16.1%