# AI Job Market: Grouped Salary Analysis

This notebook compares salaries across experience levels, job
categories, countries, and work arrangements.

In [1]:
from pathlib import Path
import pandas as pd

DATA_PATH = Path("../ai_jobs_market_2025_2026.csv")
df = pd.read_csv(DATA_PATH)

print("Dataset shape:", df.shape)
df.head()

Dataset shape: (1500, 25)

,job_id,job_title,job_category,experience_level,years_of_experience,education_required,annual_salary_usd,salary_min_usd,salary_max_usd,city,...,ai_salary_premium_pct,demand_score,demand_growth_yoy_pct,benefits_score_10,posting_year,posting_month,is_senior,is_remote_friendly,is_llm_role,salary_tier
0,AIJOB0001,AI Agent Developer,AI Engineering,Senior (6-9 yrs),7,Master's,239000.0,155000,290000,Boston,...,13.1,96,16.9,6.8,2026,3,1,0,1,Senior ($200-300k)
1,AIJOB0002,Prompt Engineer,AI Engineering,Senior (6-9 yrs),2,Bachelor's,166000.0,90000,200000,London,...,5.4,82,11.6,6.2,2026,1,1,1,1,Upper-Mid ($150-200k)
2,AIJOB0003,LLM Engineer,AI Engineering,Senior (6-9 yrs),4,Associate's,360000.0,160000,300000,Seattle,...,9.1,98,42.7,7.7,2026,1,1,1,1,Elite (>$300k)
3,AIJOB0004,Data Engineer (AI),Data Engineering,Senior (6-9 yrs),3,Bachelor's,161000.0,130000,220000,Singapore,...,12.0,88,6.7,9.5,2026,3,1,1,0,Upper-Mid ($150-200k)
4,AIJOB0005,AI Product Manager,Product,Lead (10+ yrs),5,Bootcamp/Self-taught,283000.0,140000,260000,Los Angeles,...,9.4,85,17.3,8.9,2026,1,1,1,0,Senior ($200-300k)

## 1. Salary by experience level

We compare job count and salary statistics across experience levels.

In [2]:
salary_by_experience = (
    df.groupby("experience_level")["annual_salary_usd"]
      .agg(["count", "mean", "median", "min", "max"])
      .sort_values("mean", ascending=False)
      .round(0)
)

salary_by_experience

                  count      mean    median      min       max
experience_level
Lead (10+ yrs)      381  240055.0  238000.0  90000.0  384000.0
Senior (6-9 yrs)    364  214280.0  208000.0  95000.0  374400.0
Mid (3-5 yrs)       370  175984.0  162000.0  94000.0  354000.0
Entry (0-2 yrs)     385  150039.0  145000.0  90000.0  300000.0

In [3]:
lead_mean = salary_by_experience.loc["Lead (10+ yrs)", "mean"]
entry_mean = salary_by_experience.loc["Entry (0-2 yrs)", "mean"]

salary_gap = lead_mean - entry_mean
growth_rate = salary_gap / entry_mean

print(f"Salary gap: ${salary_gap:,.0f}")
print(f"Lead premium over entry: {growth_rate:.1%}")

Salary gap: $90,016
Lead premium over entry: 60.0%

### Observation

Average salary rises consistently with experience. Lead-level roles
average $240,055, compared with $150,039 for entry-level roles, a
difference of about $90,016 or 60.0%.

The group sizes range from 364 to 385, so no experience group is
severely underrepresented in this dataset.

## 2. Salary by job category

We compare job counts and salary statistics across job categories.

In [4]:
salary_by_category = (
    df.groupby("job_category")["annual_salary_usd"]
      .agg(["count", "mean", "median"])
      .sort_values("mean", ascending=False)
      .round(0)
)

salary_by_category

                  count      mean    median
job_category
Architecture         52  251577.0  238000.0
AI Engineering      736  207982.0  194500.0
Infrastructure       55  203527.0  196000.0
Security             50  200400.0  194500.0
ML Operations        51  199216.0  189000.0
Product              70  194571.0  185000.0
Research             50  192280.0  183000.0
Data Science        127  181276.0  162000.0
Data Engineering     51  176157.0  160000.0
Robotics             74  170851.0  151500.0
Governance          122  152516.0  138500.0
Business             62  134145.0  116000.0

### Observation

Architecture has the highest average salary at $251,577, followed by
AI Engineering at $207,982. However, Architecture contains only 52
records, while AI Engineering contains 736, so the Architecture
estimate is based on a much smaller sample.

Business has the lowest average salary at $134,145. In most
categories, the mean is higher than the median, suggesting that
higher-paying roles pull the averages upward.

## 3. Salary by country

We compare salary levels and sample sizes across countries.

In [5]:
salary_by_country = (
    df.groupby("country")["annual_salary_usd"]
      .agg(["count", "mean", "median"])
      .sort_values("mean", ascending=False)
      .round(0)
)

salary_by_country

             count      mean    median
country
USA            515  226190.0  219000.0
Global          82  222044.0  221000.0
UAE             62  194226.0  186500.0
Switzerland     76  190592.0  167500.0
Australia       78  188000.0  180500.0
France          66  183152.0  160000.0
Singapore       71  181831.0  180000.0
Germany         81  181180.0  173000.0
UK              90  180644.0  167500.0
Canada          85  180588.0  159000.0
Netherlands     74  175257.0  160000.0
Japan           76  170132.0  158500.0
China           87  134287.0  140000.0
India           57  133123.0  140000.0

## 4. Salary by country and experience level

We use a multi-index to compare salary within both country and
experience-level groups.

In [6]:
salary_by_country_experience = (
    df.groupby(
        ["country", "experience_level"]
    )["annual_salary_usd"]
      .agg(["count", "mean", "median"])
      .round(0)
)

salary_by_country_experience

                              count      mean    median
country     experience_level
Australia   Entry (0-2 yrs)      10  131400.0  128500.0
            Lead (10+ yrs)       31  227774.0  209000.0
            Mid (3-5 yrs)        21  152905.0  145000.0
            Senior (6-9 yrs)     16  192375.0  184000.0
Canada      Entry (0-2 yrs)      24  137208.0  139000.0
            Lead (10+ yrs)       23  242087.0  230000.0
            Mid (3-5 yrs)        19  154737.0  150000.0
            Senior (6-9 yrs)     19  186789.0  177000.0
China       Entry (0-2 yrs)      14  128000.0  145000.0
            Lead (10+ yrs)       29  134724.0  140000.0
            Mid (3-5 yrs)        23  136826.0  141000.0
            Senior (6-9 yrs)     21  135095.0  138000.0
France      Entry (0-2 yrs)      24  134833.0  140500.0
            Lead (10+ yrs)       19  260737.0  260000.0
            Mid (3-5 yrs)        16  159375.0  150500.0
            Senior (6-9 yrs)      7  192571.0  193000.0
Germany     Entry (0-2 yrs)      16  135000.0  140500.0
            Lead (10+ yrs)       26  213523.0  204500.0
            Mid (3-5 yrs)        22  156955.0  157000.0
            Senior (6-9 yrs)     17  206529.0  197000.0
Global      Entry (0-2 yrs)      18  161000.0  154000.0
            Lead (10+ yrs)       23  280157.0  278000.0
            Mid (3-5 yrs)        18  196667.0  187500.0
            Senior (6-9 yrs)     23  231565.0  234000.0
India       Entry (0-2 yrs)      12  127917.0  135000.0
            Lead (10+ yrs)       16  129375.0  127500.0
            Mid (3-5 yrs)        12  137083.0  140000.0
            Senior (6-9 yrs)     17  137529.0  140000.0
Japan       Entry (0-2 yrs)      25  136760.0  138000.0
            Lead (10+ yrs)       15  236267.0  237000.0
            Mid (3-5 yrs)        18  150222.0  144500.0
            Senior (6-9 yrs)     18  181278.0  185000.0
Netherlands Entry (0-2 yrs)      18  147444.0  148000.0
            Lead (10+ yrs)       12  232500.0  219000.0
            Mid (3-5 yrs)        22  158500.0  154500.0
            Senior (6-9 yrs)     22  183545.0  174500.0
Singapore   Entry (0-2 yrs)      20  139950.0  145000.0
            Lead (10+ yrs)       16  232375.0  223000.0
            Mid (3-5 yrs)        17  170824.0  162000.0
            Senior (6-9 yrs)     18  193833.0  191500.0
Switzerland Entry (0-2 yrs)      26  142577.0  140500.0
            Lead (10+ yrs)       14  274214.0  269000.0
            Mid (3-5 yrs)        20  174400.0  164000.0
            Senior (6-9 yrs)     16  215688.0  232500.0
UAE         Entry (0-2 yrs)      17  132412.0  130000.0
            Lead (10+ yrs)       20  254850.0  247500.0
            Mid (3-5 yrs)        12  170750.0  172500.0
            Senior (6-9 yrs)     13  203462.0  209000.0
UK          Entry (0-2 yrs)      20  134000.0  139000.0
            Lead (10+ yrs)       20  225700.0  207500.0
            Mid (3-5 yrs)        24  161083.0  162000.0
            Senior (6-9 yrs)     26  199923.0  183000.0
USA         Entry (0-2 yrs)     141  170404.0  166000.0
            Lead (10+ yrs)      117  276956.0  275000.0
            Mid (3-5 yrs)       126  207381.0  203000.0
            Senior (6-9 yrs)    131  258985.0  248000.0

In [7]:
salary_by_country_experience.loc[
    ["USA", "China", "India"]
]

                          count      mean    median
country experience_level
USA     Entry (0-2 yrs)     141  170404.0  166000.0
        Lead (10+ yrs)      117  276956.0  275000.0
        Mid (3-5 yrs)       126  207381.0  203000.0
        Senior (6-9 yrs)    131  258985.0  248000.0
China   Entry (0-2 yrs)      14  128000.0  145000.0
        Lead (10+ yrs)       29  134724.0  140000.0
        Mid (3-5 yrs)        23  136826.0  141000.0
        Senior (6-9 yrs)     21  135095.0  138000.0
India   Entry (0-2 yrs)      12  127917.0  135000.0
        Lead (10+ yrs)       16  129375.0  127500.0
        Mid (3-5 yrs)        12  137083.0  140000.0
        Senior (6-9 yrs)     17  137529.0  140000.0

In [8]:
country_experience_table = (
    salary_by_country_experience
    .reset_index()
)

country_experience_table.head()

     country  experience_level  count      mean    median
0  Australia   Entry (0-2 yrs)     10  131400.0  128500.0
1  Australia    Lead (10+ yrs)     31  227774.0  209000.0
2  Australia     Mid (3-5 yrs)     21  152905.0  145000.0
3  Australia  Senior (6-9 yrs)     16  192375.0  184000.0
4     Canada   Entry (0-2 yrs)     24  137208.0  139000.0

In [9]:
selected_countries = country_experience_table[
    country_experience_table["country"].isin(
        ["USA", "China", "India"]
    )
]

selected_countries = selected_countries.sort_values(
    ["experience_level", "mean"],
    ascending=[True, False]
)

selected_countries

   country  experience_level  count      mean    median
52     USA   Entry (0-2 yrs)    141  170404.0  166000.0
8    China   Entry (0-2 yrs)     14  128000.0  145000.0
24   India   Entry (0-2 yrs)     12  127917.0  135000.0
53     USA    Lead (10+ yrs)    117  276956.0  275000.0
9    China    Lead (10+ yrs)     29  134724.0  140000.0
25   India    Lead (10+ yrs)     16  129375.0  127500.0
54     USA     Mid (3-5 yrs)    126  207381.0  203000.0
26   India     Mid (3-5 yrs)     12  137083.0  140000.0
10   China     Mid (3-5 yrs)     23  136826.0  141000.0
55     USA  Senior (6-9 yrs)    131  258985.0  248000.0
27   India  Senior (6-9 yrs)     17  137529.0  140000.0
11   China  Senior (6-9 yrs)     21  135095.0  138000.0

## 5. Salary by experience level and work arrangement

We compare work arrangements within each experience level to reduce
the effect of differences in seniority.

In [10]:
salary_by_experience_and_work = (
    df.groupby(
        ["experience_level", "remote_work"]
    )["annual_salary_usd"]
      .agg(["count", "mean", "median"])
      .round(0)
)

salary_by_experience_and_work

                               count      mean    median
experience_level remote_work
Entry (0-2 yrs)  Fully Remote    118  148856.0  145000.0
                 Hybrid          165  148648.0  145000.0
                 On-site         102  153657.0  145000.0
Lead (10+ yrs)   Fully Remote    116  240379.0  234000.0
                 Hybrid          181  238867.0  238000.0
                 On-site          84  242167.0  240500.0
Mid (3-5 yrs)    Fully Remote     99  185465.0  183000.0
                 Hybrid          180  170222.0  159000.0
                 On-site          91  177066.0  162000.0
Senior (6-9 yrs) Fully Remote    112  216834.0  198500.0
                 Hybrid          160  211165.0  212500.0
                 On-site          92  216589.0  207500.0

In [11]:
salary_by_experience_and_work["mean"].unstack()

remote_work       Fully Remote    Hybrid   On-site
experience_level
Entry (0-2 yrs)       148856.0  148648.0  153657.0
Lead (10+ yrs)        240379.0  238867.0  242167.0
Mid (3-5 yrs)         185465.0  170222.0  177066.0
Senior (6-9 yrs)      216834.0  211165.0  216589.0

### Observation

No single work arrangement has the highest average salary at every
experience level. On-site roles lead for entry and lead positions,
while fully remote roles lead for mid and senior positions.

For senior roles, fully remote and on-site salaries are almost
identical. Therefore, this dataset does not support the general claim
that remote work always pays more. Job category, country, and other
factors may also influence salary.

## Conclusion

- Average salary increases consistently with experience. Lead roles
  earn about 60% more than entry-level roles in this dataset.
- Architecture has the highest average salary, but its sample is much
  smaller than AI Engineering, so the result should be interpreted
  cautiously.
- The USA has the highest country-level average salary, although the
  comparison does not adjust for cost of living or differences in job
  composition.
- Fully remote work is not consistently the highest-paid arrangement
  after comparing roles within the same experience level.